<a href="https://colab.research.google.com/github/vikpy/mtechdatascience_mlcourse/blob/master/test1_q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
"""
Q 2. Classification problem using Weekly data set: -
a. Fit the logistic regression model using a training data period from 1990 to 2008, with Lag2 as the only predictor. 																				4 marks
b. Compute the confusion matrix and the overall fraction of correct predictions for the data from 2009 and 2010). Explain what the confusion matrix is telling you about the types of mistakes made by logistic regression 																		2 mark
c. Repeat experiment 1 with using KNN with K = 1					 
d. Repeat experiment 1 with using Naive Bayes		
e. Which of these methods appears to provide the best results on this data? 
"""

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import pandas as pd
import math
import random

# Q2 a]

In [15]:
data = pd.read_csv("/content/Weekly.csv")
data.head(5)

Year   Lag1   Lag2   Lag3   Lag4   Lag5    Volume  Today Direction
0  1990  0.816  1.572 -3.936 -0.229 -3.484  0.154976 -0.270      Down
1  1990 -0.270  0.816  1.572 -3.936 -0.229  0.148574 -2.576      Down
2  1990 -2.576 -0.270  0.816  1.572 -3.936  0.159837  3.514        Up
3  1990  3.514 -2.576 -0.270  0.816  1.572  0.161630  0.712        Up
4  1990  0.712  3.514 -2.576 -0.270  0.816  0.153728  1.178        Up

In [0]:
predictor = ["Lag1"]
response = ["Direction"]

In [0]:
# Down Up to 1 and 0 

def logical_convert(x):
  if str(x) == "Up":
    return 1 
  else :
    return 0 

In [0]:
data["Direction"] = data["Direction"].apply(logical_convert)

In [20]:
data.head()

Year   Lag1   Lag2   Lag3   Lag4   Lag5    Volume  Today  Direction
0  1990  0.816  1.572 -3.936 -0.229 -3.484  0.154976 -0.270          0
1  1990 -0.270  0.816  1.572 -3.936 -0.229  0.148574 -2.576          0
2  1990 -2.576 -0.270  0.816  1.572 -3.936  0.159837  3.514          1
3  1990  3.514 -2.576 -0.270  0.816  1.572  0.161630  0.712          1
4  1990  0.712  3.514 -2.576 -0.270  0.816  0.153728  1.178          1

In [24]:
data1 = data[data["Year"] >= 1990 ]
data2 = data[data["Year"] <= 2008 ]
data3 = pd.concat([data1, data2])
data3.head()

Year   Lag1   Lag2   Lag3   Lag4   Lag5    Volume  Today  Direction
0  1990  0.816  1.572 -3.936 -0.229 -3.484  0.154976 -0.270          0
1  1990 -0.270  0.816  1.572 -3.936 -0.229  0.148574 -2.576          0
2  1990 -2.576 -0.270  0.816  1.572 -3.936  0.159837  3.514          1
3  1990  3.514 -2.576 -0.270  0.816  1.572  0.161630  0.712          1
4  1990  0.712  3.514 -2.576 -0.270  0.816  0.153728  1.178          1

In [0]:
X = data3["Lag1"]
y = data3["Direction"] 

In [0]:
# Splitting the dataset into train and test sets 
from sklearn.model_selection import train_test_split 
# 80-20 ratio the model is split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/5, random_state = 0)

In [41]:
from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression(random_state = 1)
classifier.fit(X_train.values.reshape(-1,1), y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = classifier.predict(X_test.values.reshape(-1,1))

In [43]:
from sklearn.metrics import confusion_matrix 
cm  = confusion_matrix(y_test, y_pred)
cm

array([[  5, 188],
       [  5, 217]])

# Q2 b]

In [0]:
data4 = data[data["Year"] >= 2009 ]
data5 = data[data["Year"] <= 2010 ]
data6 = pd.concat([data4, data5])
X_val_new = data6["Lag1"]
y_val_new = data6["Direction"]

In [48]:
y_val_pred = classifier.predict(X_val_new.values.reshape(-1,1))
from sklearn.metrics import confusion_matrix 
cm  = confusion_matrix( y_val_new,  y_val_pred)
cm

array([[ 14, 513],
       [ 17, 649]])

In [0]:
"""
In the above confusion matrix we have 14 down directions which were predicted correctly and 649 Up directions that were predicted corretly.
513 Downs were not predicted correctly and 17 Ups were not predicted correctly
"""



# Q2 d]

In [51]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB

# instantiate the model (using the default parameters)
model = GaussianNB()
# fit the model with data
model.fit(X_train.values.reshape(-1,1),y_train)
#
y_val_pred = model.predict(X_val_new.values.reshape(-1,1))
cm  = confusion_matrix( y_val_new,  y_val_pred)
cm

array([[  0, 527],
       [  0, 666]])

# Q2 c]

In [52]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

# instantiate the model (using the default parameters)
model = KNeighborsClassifier()
# fit the model with data
model.fit(X_train.values.reshape(-1,1),y_train)
#
y_val_pred = model.predict(X_val_new.values.reshape(-1,1))
cm  = confusion_matrix( y_val_new,  y_val_pred)
cm

array([[336, 191],
       [146, 520]])

# Q2 e]

In [0]:
"""
From the confusion matrices above we can say that KNN has the highest accuracy amongst all 
"""